{{- if and .Values.encryption.enabled (eq .Values.encryption.type "ipsec") }}
{{- if .Values.encryption.ipsec.createSecret }}
{{- $keys := .Values.encryption.ipsec.keyData | required "must set encryption.ipsec.keyData when creating secret" | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.encryption.ipsec.secretName | default .Values.encryption.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if and .Values.encryption.ipsec.mountPath .Values.encryption.ipsec.keyFile }}
  {{ .Values.encryption.ipsec.keyFile }}: {{ $keys }}
  {{- else }}
  {{ .Values.encryption.keyFile }}: {{ $keys }}
  {{- end }}
{{- end }}
{{- end }}
